/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Cloner, ClonerInterface } from "../Cloner";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "clone",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101d6806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80638124b78e14610030575b600080fd5b61004361003e366004610163565b61006c565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b60006100778261007d565b92915050565b60006040517f3d602d80600a3d3981f3363d3d373d3d3d363d7300000000000000000000000081528260601b60148201527f5af43d82803e903d91602b57fd5bf3000000000000000000000000000000000060288201526037816000f091505073ffffffffffffffffffffffffffffffffffffffff811661015e576040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152601660248201527f455243313136373a20637265617465206661696c656400000000000000000000604482015260640160405180910390fd5b919050565b60006020828403121561017557600080fd5b813573ffffffffffffffffffffffffffffffffffffffff8116811461019957600080fd5b939250505056fea2646970667358221220681241f6f494c8a746b4e982957a8adaeefcae39f69d3220d3e7e6ad0ba8decb64736f6c63430008090033";

type ClonerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ClonerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Cloner__factory extends ContractFactory {
  constructor(...args: ClonerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "Cloner";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Cloner> {
    return super.deploy(overrides || {}) as Promise<Cloner>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Cloner {
    return super.attach(address) as Cloner;
  }
  connect(signer: Signer): Cloner__factory {
    return super.connect(signer) as Cloner__factory;
  }
  static readonly contractName: "Cloner";
  public readonly contractName: "Cloner";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ClonerInterface {
    return new utils.Interface(_abi) as ClonerInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Cloner {
    return new Contract(address, _abi, signerOrProvider) as Cloner;
  }
}
