/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  FactoryWidePauseWindow,
  FactoryWidePauseWindowInterface,
} from "../FactoryWidePauseWindow";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getPauseConfiguration",
    outputs: [
      {
        internalType: "uint256",
        name: "pauseWindowDuration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "bufferPeriodDuration",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5061001e6276a70042610026565b60805261004c565b6000821982111561004757634e487b7160e01b600052601160045260246000fd5b500190565b60805161011061006c6000396000818160520152607c01526101106000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80632da47c4014602d575b600080fd5b6033604c565b6040805192835260208301919091520160405180910390f35b600080427f000000000000000000000000000000000000000000000000000000000000000081101560ab57609f817f000000000000000000000000000000000000000000000000000000000000000060b6565b9362278d009350915050565b506000928392509050565b60008282101560d557634e487b7160e01b600052601160045260246000fd5b50039056fea2646970667358221220216b6733fc3bee284099f5809ad5d9cbdd2d1f81d0f89943a5648031eb10859364736f6c63430008090033";

type FactoryWidePauseWindowConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FactoryWidePauseWindowConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FactoryWidePauseWindow__factory extends ContractFactory {
  constructor(...args: FactoryWidePauseWindowConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "FactoryWidePauseWindow";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<FactoryWidePauseWindow> {
    return super.deploy(overrides || {}) as Promise<FactoryWidePauseWindow>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): FactoryWidePauseWindow {
    return super.attach(address) as FactoryWidePauseWindow;
  }
  connect(signer: Signer): FactoryWidePauseWindow__factory {
    return super.connect(signer) as FactoryWidePauseWindow__factory;
  }
  static readonly contractName: "FactoryWidePauseWindow";
  public readonly contractName: "FactoryWidePauseWindow";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FactoryWidePauseWindowInterface {
    return new utils.Interface(_abi) as FactoryWidePauseWindowInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FactoryWidePauseWindow {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as FactoryWidePauseWindow;
  }
}
